INSERT INTO `items` (`name`, `label`, `weight`) VALUES
    ('water_bottle', 'Water Bottle', 1),
    ('sandwich', 'Sandwich', 1),
    ('bandage', 'Bandage', 1),
    ('weapon_flashlight', 'Flashlight', 1),
    ('goldpan', 'Gold pan', 1),
    ('pickaxe', 'Pickaxe', 1),
    ('miningdrill', 'Mining Drill', 1),
    ('mininglaser', 'Mining Laser', 1),
    ('drillbit', 'Drill Bit', 1),
    ('metalscrap', 'Metal scrap', 1),
    ('stone', 'Stone', 1),
    ('bottle', 'Bottle', 1),
    ('can', 'Can', 1),
    ('uncut_ruby', 'Uncut ruby', 1),
    ('uncut_emerald', 'Uncut emerald', 1),
    ('uncut_diamond', 'Uncut diamond', 1),
    ('uncut_sapphire', 'Uncut sapphire', 1),
    ('copperore', 'Copper Ore', 1),
    ('ironore', 'Iron Ore', 1),
    ('goldore', 'Gold Ore', 1),
    ('silverore', 'Silver Ore', 1),
    ('carbon', 'Carbon', 1),
    ('copper', 'Copper', 1),
    ('goldingot', 'Gold Ingot', 1),
    ('iron', 'Iron', 1),
    ('steel', 'Steel', 1),
    ('aluminum', 'Aluminium', 1),
    ('glass', 'Glass', 1),
    ('emerald', 'Emerald', 1),
    ('ruby', 'Ruby', 1),
    ('diamond', 'Diamond', 1),
    ('sapphire', 'Sapphire', 1),
    ('diamond_ring', 'Diamond Ring', 1),
    ('emerald_ring', 'Emerald Ring', 1),
    ('ruby_ring', 'Ruby Ring', 1),
    ('sapphire_ring', 'Sapphire Ring', 1),
    ('diamond_ring_silver', 'Diamond Silver Ring', 1),
    ('emerald_ring_silver', 'Emerald Silver Ring', 1),
    ('ruby_ring_silver', 'Ruby Silver Ring', 1),
    ('sapphire_ring_silver', 'Sapphire Silver Ring', 1),
    ('diamond_earring', 'Diamond Ear Ring', 1),
    ('emerald_earring', 'Emerald Ear Ring', 1),
    ('ruby_earring', 'Ruby Ear Ring', 1),
    ('sapphire_earring', 'Sapphire Ear Ring', 1),
    ('diamond_earring_silver', 'Diamond Silver Ear Ring', 1),
    ('emerald_earring_silver', 'Emerald Silver Ear Ring', 1),
    ('ruby_earring_silver', 'Ruby Silver Ear Ring', 1),
    ('sapphire_earring_silver', 'Sapphire Silver Ear Ring', 1),
    ('diamond_necklace', 'Diamond Necklace', 1),
    ('ruby_necklace', 'Ruby Necklace', 1),
    ('sapphire_necklace', 'Sapphire Necklace', 1),
    ('emerald_necklace', 'Emerald Necklace', 1),
    ('diamond_necklace_silver', "Diamond Silver Necklace", 1),
    ('ruby_necklace_silver', "Ruby Silver Necklace", 1),
    ('sapphire_necklace_silver', 'Sapphire Silver Necklace', 1),
    ('emerald_necklace_silver', 'Emerald Silver Necklace', 1),
    ('gold_ring', 'Gold Ring', 1),
    ('goldchain', 'Gold Chain', 1),
    ('goldearring', 'Gold Ear Ring', 1),
    ('silver_ring', 'Silver Ring', 1),
    ('silverchain', 'Silver Chain', 1),
    ('silverearring', 'Silver Ear Ring', 1);